
[disclaimer]
	#Displays the disclaimer
	"Display Disclaimer?" = false

[death]
	#Display death effect
	"Display Death Effect?" = false

[shake]
	#Does this mod make your window shake
	"Window Shaking?" = true

