
["Easter eggs"]
	#Is observe a nerd?
	"Nerdy Observe" = false
	#Adds an epic tiger to the game
	"Epic Tiger" = false
	#Is agony bottleable? (is bottleable even a word?)
	"Bottled Agony" = false

